accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
 path('admin/', admin.site.urls),
 path('', include('learning_logs.urls')),
 path('accounts/', include('accounts.urls')),
]

pizzeria_project/pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
    # Page for adding a new topic.
    
]

pizzeria_project/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name

pizzeria_project/pizzas/views.py
from django.shortcuts import render

from .models import Pizza, Topping
# Create your views here.
def index(request):
 return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzeria_project/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>
{% block content %}
{% endblock content %}
  

pizzeria_project/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
    <p>Pizzeria</p>
    <p>Hello, World!</p>
{% endblock content %}

pizzeria_project/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}
{% block content %}
    <p>Pizza: {{ pizza.name }}</p>

    <p>Toppings:</p>
    <ul>
        {% for topping in toppings %}
            <li>
                <p>{{ topping.name|linebreaks }}</p>
            </li>
        {% empty %}
            <li>There are no toppings for this pizza yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

pizzeria_project/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}
{% block content %}
    <p>Pizzas</p>
    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">
                    {{ pizza.name }}</a></li>
            </li>
        {% empty %}
            <li>No pizzas have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}