accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
]

blog/blogs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('pages/', views.pages, name='pages'),
    path('pages/<int:page_id>/', views.page, name='page'),
    path('new_page/', views.new_page, name='new_page'),
    path('new_post/<int:page_id>/', views.new_post, name='new_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
 path('admin/', admin.site.urls),
 path('', include('learning_logs.urls')),
 path('accounts/', include('accounts.urls')),
]

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Page(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

class Post(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.text

blog/blogs/forms.py
from django import forms

from .models import Page, Post

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['name']
        labels = {'text': ''}

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:index')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Page, Post

from .forms import PageForm, PostForm

# Create your views here.
def index(request):
    return render(request, 'blogs/index.html')

def pages(request):
    pages = Page.objects.order_by('date_added')
    context = {'pages': pages}
    return render(request, 'blogs/pages.html', context)

def page(request, page_id):
    page = Page.objects.get(id=page_id)
    posts = page.post_set.order_by('-date_added')
    context = {'page': page, 'posts': posts}
    return render(request, 'blogs/page.html', context)

@login_required
def new_page(request):
    check_topic_owner(request, page)
    if request.method != 'POST':
        form = PageForm()
    else:
        form = PageForm(data=request.POST)
        if form.is_valid():
            new_page = form.save(commit = False)
            new_page.owner = request.user
            new_page.save()
            return redirect('blogs:pages')

    context = {'form': form}
    return render(request, 'blogs/new_page.html', context)

@login_required
def new_post(request, page_id):
    page = Page.objects.get(id=page_id)
    check_topic_owner(request, page)

    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.page = page
            new_post.save()
            return redirect('blogs:page', page_id=page_id)

    context = {'page': page, 'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    post = Post.objects.get(id=post_id)
    page = post.page
    check_topic_owner(request, page)
    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:page', page_id=page.id)

    context = {'post': post, 'page': page, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def check_topic_owner(request, page):
    if page.owner != request.user:
        raise Http404

blog/blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Learning Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blogs:index' %}">
          Blog Host</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:pages' %}">
              Blogs</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                  Register</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                  Log in</a></li>
          {% endif %}

        </ul> <!-- End of account-related links -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-secondary btn-sm'>
              Log out</button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}

    <p><a href="{% url 'blogs:page' page.id %}">{{page}}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'blogs:edit_post' post.id %}" method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Blog Host</h1>
      
      <p class="lead">Create your own blog, and share it with the world.</p>

      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

blog/blogs/templates/blogs/new_page.html
{% extends "blogs/base.html" %}
{% block content %}
    <p>Add a new page:</p>

    <form action=""{% url 'blogs:new_page' %} method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button name="submit">Add page</button>
    </form>

{% endblock content %}

blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p><a href="{% url 'blogs:page' page.id %}">{{ page }}</a></p>

    <p>Add a new post:</p>
    <form action="{% url 'blogs:new_post' page.id %}" method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button name="submit">Add post</button>
    </form>

{% endblock content %}

blog/blogs/templates/blogs/page.html
{% extends 'blogs/base.html' %}
{% block content %}
    <p>Page: {{ page.name }}</p>

    <p>Posts:</p>
    <p>
        <a href="{% url 'blogs:new_post' page.id %}">Add new post</a>
    </p>
    <ul>
        {% for post in posts %}
            <li>
                <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ post.text|linebreaks }}</p>
                <p>
                    <a href="{% url 'blogs:edit_post' post.id %}">
                    Edit post</a>
                </p>
            </li>
        {% empty %}
            <li>There are no posts for this page yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

blog/blogs/templates/blogs/pages.html
{% extends 'blogs/base.html' %}
{% block content %}
    <p>Page</p>
    <ul>
        {% for page in pages %}
            <li>
                <a href="{% url 'blogs:page' page.id %}">
                    {{ page.name }}</a></li>
            </li>
        {% empty %}
            <li>No pages have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'blogs:new_page' %}">Add a new page</a>

{% endblock content %}